// console.log(null * 5);
// console.log(undefined * 5);
// console.log(undefined * null);
// console.log(undefined * 0);
// console.log(null * 0);
console.log('5' - 3); //NUM
console.log('5' + 3); //STRING
console.log('5' + '3'); //STRING
console.log('5' - '3'); //NUM
console.log(+'5' - 3); //NUM
console.log(+'5' + 3); //NUM